### ISSUE TITLE
[Sub-Task] 프로젝트 세팅

### ISSUE THREAD

**Issue by humonnom** [humonnom/react-practice-form#2]
- 총 예상소요시간: 1시간 10분
- 총 실제소요시간:  1시간 15분
- [x] Create React App 생성, 깃헙 연결
   - 예상소요시간:  10분
   - 실제소요시간: 20분
- [x] Prettier, Eslint 세팅
   - 예상소요시간: 1시간 
   - 실제소요시간: 40분
- [x] vite로 변경하여  다시 세팅
   - CRA 설정이 번거로워 세팅을 다시 함
   - 예상소요시간: 30분
   - 실제소요시간: 15분
